# -*- coding: utf-8 -*-
"""ModelPredict_0828.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XH75YaGqojvTFN9vgqnIrwDZWZmmLhbF
"""

from xgboost import XGBClassifier
import pandas as pd
file_path = '경로'
file_name = 'Inbody_deal_complete_predict.model'

# 모델 불러오기
new_xgb_model = XGBClassifier() # 모델 초기화
new_xgb_model.load_model(file_path+file_name) # 모델 불러오기

"""
ex.
2021 = 1.775041
8 = 0.454290228
31 = 1.704802765
leadsource = Inbound : 0.720979333, Outbound : -0.010379578, referrence:1.452338244, dealer reference: 0.17246015
territory = w1: 0.175056198, w2:-0.263811991, east:-1.006072469,south:-0.676520868, north:0.424721715
Industry = fitness: -0.36018435, hospital:  -0.400201708, private enterprise:  -0.400263211, individual: -0.105478339
"""

# 받아온 value
year =
month =
lead_source =
territory =
industry = 

# 'Year', 'Month', 'Day', 'LeadSource', 'Territory', 'Industry' 순으로 기입
x = [year,month,lead_source,territory,industry]
x = pd.DataFrame([x], columns=['Year', 'Month', 'Day', 'LeadSource', 'Territory', 'Industry'])
model.predict(x)
# Input
X = [year,month,lead_source,territory,industry]

# 예측, output은 1 - success or 0 - loose
pred_y = new_xgb_model.predict(X)